# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern_cov <- function(distance, kappa, phi) {
    .Call(`_spatialT2_matern_cov`, distance, kappa, phi)
}

conditional_covariance <- function(C, vec_C, C_i) {
    .Call(`_spatialT2_conditional_covariance`, C, vec_C, C_i)
}

phi_rcpp_arm <- function(a, x_m, w, w_neighbors, solve_C, cov_C, cond_C, vec_C, n_obs, gammar, tau, y, sig) {
    .Call(`_spatialT2_phi_rcpp_arm`, a, x_m, w, w_neighbors, solve_C, cov_C, cond_C, vec_C, n_obs, gammar, tau, y, sig)
}

w_rcpp_arm <- function(gammar, phi, w_neighbors, y, tau, beta, sig) {
    .Call(`_spatialT2_w_rcpp_arm`, gammar, phi, w_neighbors, y, tau, beta, sig)
}

mvrnormArma <- function(mean, variance) {
    .Call(`_spatialT2_mvrnormArma`, mean, variance)
}

gamma_rcpp_arm <- function(a, n_obs, vec_C, solve_C, cov_C, phi, w_neighbors, w, sig) {
    .Call(`_spatialT2_gamma_rcpp_arm`, a, n_obs, vec_C, solve_C, cov_C, phi, w_neighbors, w, sig)
}

data_loop_rcpp_arm <- function(a, n_obs, D, w, n_neighbors, m_location, W, tau, phi, y, beta, sig, kappa, nu) {
    .Call(`_spatialT2_data_loop_rcpp_arm`, a, n_obs, D, w, n_neighbors, m_location, W, tau, phi, y, beta, sig, kappa, nu)
}

data_loop_rcpp_no_nugget <- function(a, n_obs, vec_C, solve_C, cov_C, cond_C, n_neighbors, m_location, W, tau, phi, y, beta, sig) {
    .Call(`_spatialT2_data_loop_rcpp_no_nugget`, a, n_obs, vec_C, solve_C, cov_C, cond_C, n_neighbors, m_location, W, tau, phi, y, beta, sig)
}

posterior_marginal <- function(n_neighbors, n_obs, D, Y_post, a, kappa, y, W, phi, sigma, tau, small) {
    .Call(`_spatialT2_posterior_marginal`, n_neighbors, n_obs, D, Y_post, a, kappa, y, W, phi, sigma, tau, small)
}

rcpparma_hello_world <- function() {
    .Call(`_spatialT2_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_spatialT2_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_spatialT2_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_spatialT2_rcpparma_bothproducts`, x)
}

